services:
  node:
    image: tamartayar/personal-project:node
    build: ./node
    ports:
      - "3000:3000"
  php:
    image: tamartayar/personal-project:php
    build: ./php
    ports:
      - "8088:80"
  mysql:
    image: mysql/mysql-server:8.0.28
    ports:
      - "3306:3306"
    environment:
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
